export const mockDatabase = [
    {
        id: 1,
        name: 'John',
        surname: 'Doe',
        email: 'john@doe.com',
    },
    {
        id: 2,
        name: 'Jane',
        surname: 'Smith',
        email: 'jane@smith.com',
    },
    {
        id: 3,
        name: 'Michael',
        surname: 'Johnson',
        email: 'michael@johnson.com',
    },
    {
        id: 4,
        name: 'Emily',
        surname: 'Davis',
        email: 'emily@davis.com',
    },
    {
        id: 5,
        name: 'Chris',
        surname: 'Brown',
        email: 'chris@brown.com',
    },
    {
        id: 6,
        name: 'Sarah',
        surname: 'Wilson',
        email: 'sarah@wilson.com',
    },
    {
        id: 7,
        name: 'David',
        surname: 'Martinez',
        email: 'david@martinez.com',
    },
    {
        id: 8,
        name: 'Emma',
        surname: 'Garcia',
        email: 'emma@garcia.com',
    },
    {
        id: 9,
        name: 'Daniel',
        surname: 'Taylor',
        email: 'daniel@taylor.com',
    },
    {
        id: 10,
        name: 'Sophia',
        surname: 'Anderson',
        email: 'sophia@anderson.com',
    },
    {
        id: 11,
        name: 'James',
        surname: 'Lee',
        email: 'james@lee.com',
    },
    {
        id: 12,
        name: 'Olivia',
        surname: 'Moore',
        email: 'olivia@moore.com',
    },
    {
        id: 13,
        name: 'Robert',
        surname: 'Clark',
        email: 'robert@clark.com',
    },
    {
        id: 14,
        name: 'Isabella',
        surname: 'Walker',
        email: 'isabella@walker.com',
    },
    {
        id: 15,
        name: 'William',
        surname: 'Lopez',
        email: 'william@lopez.com',
    },
    {
        id: 16,
        name: 'Mia',
        surname: 'Harris',
        email: 'mia@harris.com',
    },
    {
        id: 17,
        name: 'Benjamin',
        surname: 'Lewis',
        email: 'benjamin@lewis.com',
    },
    {
        id: 18,
        name: 'Charlotte',
        surname: 'Young',
        email: 'charlotte@young.com',
    },
    {
        id: 19,
        name: 'Ethan',
        surname: 'King',
        email: 'ethan@king.com',
    },
    {
        id: 20,
        name: 'Amelia',
        surname: 'Scott',
        email: 'amelia@scott.com',
    }
];
